name: Validate PR
on:
  push:
jobs:
  build:
    name: form-controls
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.17.0
        uses: actions/setup-node@v2
        with:
          node-version: 14.17.0
      - run: yarn
      - run: yarn build
      - run: yarn test 
